name: Manually trigger an Azure Machine Learning job

on:
  push:
    branches:
      - 'main'

jobs:
  dev_train:
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Trigger Azure Machine Learning job
      run: 
        az ml job create --file src/job.yml --resource-group gwg_dev_ml --workspace-name gwg_dev_ws --stream

  prod_train:
    runs-on: ubuntu-latest
    environment: prod
    needs: dev_train
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Trigger Azure Machine Learning job
      run: 
        az ml job create --file src/job2.yml --resource-group gwg_dev_ml --workspace-name gwg_dev_ws --stream