name: Workflow triggered by pull request

on: [pull_request]

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
    - name: check out repo
      uses: actions/checkout@test
    - name: Use Python version 3.8
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'
    - name: Install flake8
      run:
        python -m pip install flake8
    - name: Run linting tests
      run: 
        flake8 scr/model/